### ISSUE TITLE
Historical sync: Support Cancun

### ISSUE THREAD

**Issue by hai-rise** [risechain/reth#4]

**Comment by yutianwu** [comment]
Hi, is there a performance result for the PEVM integration?

**Comment by hai-rise** [comment]
@yutianwu Admittedly the speedup was underwhelming... Ethereum mainnet blocks are so small they don't justify the thread overheads. There was no speedup until Berlin, and only 1.33x~1.77x afterwards. The current Reth integration is also frictional with many `pevm` <> `revm` conversions. We've since moved our focus towards:
- Gigagas blocks like in our rollup.
- Advanced mempool for block building.
- https://github.com/risechain/pevm/issues/350 for historical sync.
- https://github.com/risechain/pevm/issues/382 (to only resume Ethereum support after this one).

**Comment by yutianwu** [comment]
thanks for the sharing~
